services:
  uploader:
    restart: always
    image: uploader:latest
    build: "."
    ports:
      - 8080:8080
    environment:
      - SWAGGER_ENABLED=true
      - DEBUG=true
      - PORT=8080
      - GCS_KEY_PATH=${GCS_KEY_PATH}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
    networks:
      - my-network

networks:
  my-network: null
