services:
  ecommerce_db:
    image: postgres:latest
    container_name: ecommerce_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - 5440:5432
    networks:
      - my-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  ecommerce:
    restart: always
    image: ecommerce:latest
    depends_on:
      - ecommerce_db
    build: "."
    ports:
      - 8080:8080
    environment:
      - SWAGGER_ENABLED=true
      - DEBUG=true
      - PORT=8080
      - DB_HOST=ecommerce_db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_NAME=postgres
      - DB_PASSWORD=admin
    networks:
      - my-network

networks:
  my-network: null
