// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "ecommerce/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

// FilterProducts provides a mock function with given fields: ctx, filter, orderBy
func (_m *IRepository) FilterProducts(ctx context.Context, filter models.ProductFilter, orderBy *models.ProductOrderBy) ([]models.Product, error) {
	ret := _m.Called(ctx, filter, orderBy)

	var r0 []models.Product
	if rf, ok := ret.Get(0).(func(context.Context, models.ProductFilter, *models.ProductOrderBy) []models.Product); ok {
		r0 = rf(ctx, filter, orderBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.ProductFilter, *models.ProductOrderBy) error); ok {
		r1 = rf(ctx, filter, orderBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewIRepository creates a new instance of IRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRepository(t mockConstructorTestingTNewIRepository) *IRepository {
	mock := &IRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
