// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// IUploader is an autogenerated mock type for the IUploader type
type IUploader struct {
	mock.Mock
}

// Upload provides a mock function with given fields: ctx, name, file
func (_m *IUploader) Upload(ctx context.Context, name string, file io.Reader) error {
	ret := _m.Called(ctx, name, file)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = rf(ctx, name, file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIUploader interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUploader creates a new instance of IUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUploader(t mockConstructorTestingTNewIUploader) *IUploader {
	mock := &IUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
